# Set build version format here instead of in the admin panel
version: "{build}"

# Do not build on gh tags
skip_tags: true

# Test against these versions of Node.js
environment:

  matrix:
  - nodejs_version: "Current"
  - nodejs_version: "LTS"

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

install:
  # Install Chrome
  - choco install -y googlechrome --ignore-checksums
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  - set PATH=%APPDATA%\yarn;%PATH%
  - yarn

# Cache node_modules for faster builds
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests and build
  - yarn run test
  - yarn run build

before_test:
  - npm run build

# Don't build the app
build: off

notifications:
- provider: Email
  to:
  - legrd.kevin@gmail.com
  subject: 'Build failed: purr-react'
  message: The continuous integration build failed. See https://ci.appveyor.com/project/Manoz/purr-react/ for details.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
